services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5004:5000"
    volumes:
      - .:/app
    command: python app.py

  frontend:
    build:
      context: ./my-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true

